export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Shop } from './Shop'
export { default as Aboutus } from './Aboutus'
export { default as Contactus } from './Contactus'
export { default as Footer } from './Footer'
export { default as SmoothScroll } from './SmoothScroll'